version: '2'

services:

  http2s3:
    image: docker.io/editorbank/http2s3
    build: .
    ports:
      - 8001:8000
    environment:
     - IN_PORT=8000
     - S3_PROTOCOL=http
     - S3_HOST=s3svr
     - S3_PORT=8000
     - S3_ACCESS_KEY=YOUR-ACCESS-KEY-HERE
     - S3_SECRET_KEY=YOUR-SECRET-KEY-HERE
    # command:
    #  - sleep
    #  - 1d
    networks:
     - default
    depends_on:
     - s3svr

  s3svr:
    image: docker.io/scality/s3server
    ports:
      - 8002:8000
    environment:
     - SCALITY_ACCESS_KEY_ID=YOUR-ACCESS-KEY-HERE
     - SCALITY_SECRET_ACCESS_KEY=YOUR-SECRET-KEY-HERE
    volumes:
     - ./.tmp/http2s3-Data:/usr/src/app/localData
     - ./.tmp/http2s3-Metadata:/usr/src/app/localMetadata
    networks:
      - default

networks:
    default:
        driver:  bridge
        enable_ipv6: false
