# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-01-06T12:21:32Z"
  labels:
    app: http2s3
  name: http2s3
spec:
  containers:
  - args:
    - nginx
    - -c
    - /etc/nginx/http2s3.nginx.conf
    image: localhost/editorbank/http2s3:latest
    name: http2s3
    ports:
    - containerPort: 80
      hostPort: 8500
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    stdin: true
    tty: true
